// <auto-generated />
namespace expenseTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MigratedDbemailovveride : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigratedDbemailovveride));
        
        string IMigrationMetadata.Id
        {
            get { return "201709070737416_MigratedDb email ovveride"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
